"""
Custom template context processors.
"""


def csp_nonce(request):
    """
    Add CSP nonce to template context.

    The nonce is generated by CSPMiddleware and attached to the request.
    """
    return {"csp_nonce": getattr(request, "csp_nonce", "")}
