# Generated by Django 5.2.8 on 2026-01-05
# User model moved from games to core
#
# This migration creates the games_user table if it doesn't exist.
# - Fresh databases: Creates the table
# - Production: Table already exists from games.0060, so creation is skipped
#
# No manual --fake step required!

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import connection, migrations, models


def create_user_table_if_needed(apps, schema_editor):
    """Create games_user table only if it doesn't exist."""
    # Check if table already exists (from games.0060 on production)
    tables = connection.introspection.table_names()
    if "games_user" in tables:
        # Table exists (production) - nothing to do
        return

    # Table doesn't exist (fresh database) - create it using Django's schema editor
    # This handles PostgreSQL vs SQLite differences automatically

    # Get the User model from state (not the actual model)
    User = apps.get_model("core", "User")

    # Create the table
    with schema_editor.connection.schema_editor() as editor:
        editor.create_model(User)


def reverse_create_user_table(apps, schema_editor):
    """Reverse migration - don't drop the table, it may have data."""
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    # Run before games.0060 and account migrations that reference User
    run_before = [
        ("games", "0060_custom_user_model"),
        ("account", "0001_initial"),
        ("admin", "0001_initial"),
        ("socialaccount", "0001_initial"),
    ]

    operations = [
        # Register the model in Django's state first
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="User",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "password",
                            models.CharField(max_length=128, verbose_name="password"),
                        ),
                        (
                            "last_login",
                            models.DateTimeField(
                                blank=True, null=True, verbose_name="last login"
                            ),
                        ),
                        (
                            "is_superuser",
                            models.BooleanField(
                                default=False,
                                help_text="Designates that this user has all permissions without explicitly assigning them.",
                                verbose_name="superuser status",
                            ),
                        ),
                        (
                            "username",
                            models.CharField(
                                error_messages={
                                    "unique": "A user with that username already exists."
                                },
                                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                                max_length=150,
                                unique=True,
                                validators=[
                                    django.contrib.auth.validators.UnicodeUsernameValidator()
                                ],
                                verbose_name="username",
                            ),
                        ),
                        (
                            "first_name",
                            models.CharField(
                                blank=True, max_length=150, verbose_name="first name"
                            ),
                        ),
                        (
                            "last_name",
                            models.CharField(
                                blank=True, max_length=150, verbose_name="last name"
                            ),
                        ),
                        (
                            "email",
                            models.EmailField(
                                blank=True, max_length=254, verbose_name="email address"
                            ),
                        ),
                        (
                            "is_staff",
                            models.BooleanField(
                                default=False,
                                help_text="Designates whether the user can log into this admin site.",
                                verbose_name="staff status",
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(
                                default=True,
                                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                                verbose_name="active",
                            ),
                        ),
                        (
                            "date_joined",
                            models.DateTimeField(
                                default=django.utils.timezone.now,
                                verbose_name="date joined",
                            ),
                        ),
                        ("email_subscribed", models.BooleanField(default=False)),
                        (
                            "unsubscribe_token",
                            models.CharField(
                                blank=True,
                                db_index=True,
                                max_length=64,
                                null=True,
                                unique=True,
                            ),
                        ),
                        (
                            "date_subscribed",
                            models.DateTimeField(blank=True, null=True),
                        ),
                        (
                            "groups",
                            models.ManyToManyField(
                                blank=True,
                                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                                related_name="user_set",
                                related_query_name="user",
                                to="auth.group",
                                verbose_name="groups",
                            ),
                        ),
                        (
                            "user_permissions",
                            models.ManyToManyField(
                                blank=True,
                                help_text="Specific permissions for this user.",
                                related_name="user_set",
                                related_query_name="user",
                                to="auth.permission",
                                verbose_name="user permissions",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "games_user",
                        "swappable": "AUTH_USER_MODEL",
                    },
                    managers=[
                        ("objects", django.contrib.auth.models.UserManager()),
                    ],
                ),
            ],
            database_operations=[],
        ),
        # Then conditionally create the table (for fresh databases only)
        migrations.RunPython(
            create_user_table_if_needed,
            reverse_create_user_table,
        ),
    ]
