# Generated by Django 5.2.8 on 2026-01-05 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0079_add_media_type_to_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=210, null=True)),
                ('goodreads_id', models.CharField(blank=True, db_index=True, help_text='GoodReads author ID', max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, null=True, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='books.bookgenre')),
            ],
            options={
                'verbose_name': 'Book Genre',
                'verbose_name_plural': 'Book Genres',
                'ordering': ['level', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('name_normalized', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=210, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(db_index=True)),
                ('year_published', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('year_rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('decade_rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('goodreads_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('wikidata_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='books.author')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='books.bookgenre')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('type', models.CharField(db_index=True, default='E', max_length=1)),
                ('order', models.PositiveIntegerField(null=True, unique=True)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_lists', to='games.publication')),
            ],
            options={
                'ordering': ['order', 'type', 'publisher', 'year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GoodreadsBookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodreads_id', models.CharField(db_index=True, max_length=50)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goodreads_book_data_set', to='books.book')),
            ],
            options={
                'verbose_name': 'GoodReads Book Data',
                'verbose_name_plural': 'GoodReads Book Data',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='primary_goodreads_book_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_book', to='books.goodreadsbookdata'),
        ),
        migrations.CreateModel(
            name='WikipediaBookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('page_title', models.CharField(db_index=True, max_length=300)),
                ('primary_genre', models.CharField(blank=True, max_length=200, null=True)),
                ('all_genres', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wikipedia_book_data_set', to='books.book')),
            ],
            options={
                'verbose_name': 'Wikipedia Book Data',
                'verbose_name_plural': 'Wikipedia Book Data',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='primary_wikipedia_book_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_book', to='books.wikipediabookdata'),
        ),
        migrations.CreateModel(
            name='BookListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='books.book')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.booklist')),
            ],
            options={
                'indexes': [models.Index(fields=['list', 'rank'], name='books_bookl_list_id_cff43c_idx'), models.Index(fields=['book', 'list'], name='books_bookl_book_id_5d199f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodreads_id', models.CharField(db_index=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'goodreads_id')},
            },
        ),
        migrations.CreateModel(
            name='WantToReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodreads_id', models.CharField(db_index=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='want_to_read_by', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_read_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Want to Read Book',
                'verbose_name_plural': 'Want to Read Books',
                'unique_together': {('user', 'goodreads_id')},
            },
        ),
    ]
