# Generated by Django 5.2.8 on 2026-01-07 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('type', models.CharField(choices=[('A', 'All time'), ('E', 'End of year'), ('M', 'Miscellaneous'), ('D', 'Decade')], db_index=True, default='E', max_length=1)),
                ('order', models.PositiveIntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Book List',
                'verbose_name_plural': 'Book Lists',
                'db_table': 'books_booklist',
                'ordering': ['order', 'type', 'publisher', 'year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Book Publication',
                'verbose_name_plural': 'Book Publications',
                'db_table': 'books_bookpublication',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='booklistmembership',
            options={'verbose_name': 'Book List Membership', 'verbose_name_plural': 'Book List Memberships'},
        ),
        migrations.AlterField(
            model_name='booklistmembership',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booklistmembership',
            name='list',
            field=models.ForeignKey(help_text='The list this book appears on', on_delete=django.db.models.deletion.CASCADE, to='books.booklist'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='books.bookpublication'),
        ),
        migrations.AddIndex(
            model_name='booklist',
            index=models.Index(fields=['type', 'year'], name='books_bookl_type_146cc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booklist',
            unique_together={('publisher', 'name', 'year')},
        ),
    ]
