#!/usr/bin/env python
"""
Generate the scoped forum stylesheet.

django-machina ships Bootstrap-based CSS whose global rules (a, body,
.btn, ...) would restyle the site's DaisyUI sidebar/nav on forum pages.
This script rewrites machina's two stylesheets so every selector is
prefixed with `#main-content` (the main content column in base.html,
which excludes the sidebar, mobile nav and modals) and writes the
combined result to games/static/games/css/machina-scoped.css.

Re-run after upgrading django-machina:

    venv/bin/python scripts/scope_machina_css.py

Requires tinycss2 (pip install tinycss2).
"""

from pathlib import Path

import tinycss2

SCOPE = "#main-content"
ROOT_SELECTORS = {"html", "body", ":root"}
# Bootstrap's html/body rules get re-targeted at the scope element. Only
# typography may survive that mapping: properties like margin/background
# would override the site layout (e.g. the sidebar offset on #main-content).
SAFE_ROOT_PROPS = {
    "font-family",
    "font-size",
    "font-weight",
    "line-height",
    "color",
    "text-align",
    "-webkit-text-size-adjust",
    "-ms-text-size-adjust",
}
# At-rules whose body is another stylesheet (recurse into them)
NESTED_AT_RULES = {"media", "supports"}
# At-rules whose prelude/body must not be touched
VERBATIM_AT_RULES = {"keyframes", "-webkit-keyframes", "font-face", "page"}


def split_top_level_commas(selector_text):
    """Split a selector list on commas outside (), [] pairs."""
    parts, depth, current = [], 0, []
    for char in selector_text:
        if char in "([":
            depth += 1
        elif char in ")]":
            depth -= 1
        if char == "," and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(char)
    parts.append("".join(current))
    return parts


def scope_selector(selector):
    """Prefix a single compound selector with the scope."""
    selector = selector.strip()
    if not selector:
        return selector
    # Map root-level selectors onto the scope element itself
    first_token = selector.split()[0].split(":")[0].split(".")[0] or selector
    if selector in ROOT_SELECTORS:
        return SCOPE
    if first_token in {"html", "body"}:
        # e.g. "body.modal-open" -> "#main-content.modal-open",
        # "html body" handled by replacing the root part
        rest = selector[len(first_token) :]
        if rest.startswith(" "):
            return f"{SCOPE}{rest}"
        return f"{SCOPE}{rest}"
    return f"{SCOPE} {selector}"


def filter_root_declarations(content_tokens):
    """Keep only typography declarations for html/body-mapped rules."""
    kept = []
    for decl in tinycss2.parse_declaration_list(content_tokens):
        if decl.type == "declaration" and decl.lower_name in SAFE_ROOT_PROPS:
            kept.append(
                f"{decl.name}:{tinycss2.serialize(decl.value).strip()}"
                f"{'!important' if decl.important else ''}"
            )
    return ";".join(kept)


def scope_rules(rules):
    out = []
    for rule in rules:
        if rule.type == "qualified-rule":
            prelude = tinycss2.serialize(rule.prelude)
            selectors = [s.strip() for s in split_top_level_commas(prelude)]
            scoped = ",".join(scope_selector(s) for s in selectors)
            if any(
                s in ROOT_SELECTORS or s.split()[0] in {"html", "body"}
                for s in selectors
                if s
            ):
                body = filter_root_declarations(rule.content)
                if not body:
                    continue
            else:
                body = tinycss2.serialize(rule.content)
            out.append(f"{scoped}{{{body}}}")
        elif rule.type == "at-rule":
            name = rule.lower_at_keyword
            prelude = tinycss2.serialize(rule.prelude).strip()
            if rule.content is None:
                out.append(f"@{rule.at_keyword} {prelude};")
            elif name in NESTED_AT_RULES:
                inner = scope_rules(tinycss2.parse_rule_list(rule.content))
                out.append(f"@{rule.at_keyword} {prelude}{{{''.join(inner)}}}")
            else:
                # @font-face, @keyframes etc. - copy verbatim
                body = tinycss2.serialize(rule.content)
                out.append(f"@{rule.at_keyword} {prelude}{{{body}}}")
        elif rule.type == "comment":
            continue
        elif rule.type == "error":
            raise SystemExit(f"CSS parse error: {rule.message}")
    return out


def main():
    import machina

    machina_css = Path(machina.MACHINA_MAIN_STATIC_DIR) / "css"
    sources = [
        machina_css / "machina.board_theme.vendor.min.css",
        machina_css / "machina.board_theme.min.css",
    ]
    chunks = [
        "/* Generated by scripts/scope_machina_css.py - do not edit.\n"
        "   machina's Bootstrap CSS scoped under #main-content so it cannot\n"
        "   restyle the DaisyUI sidebar/nav chrome on forum pages. */"
    ]
    for source in sources:
        rules = tinycss2.parse_stylesheet(
            source.read_text(encoding="utf-8"),
            skip_whitespace=True,
        )
        css = "".join(scope_rules(rules))
        # The originals live at static/css/ and reference static/fonts/ as
        # ../fonts/; this file lives one level deeper (games/css/), so the
        # relative font URLs need one extra parent segment.
        css = css.replace("url(../fonts/", "url(../../fonts/")
        chunks.append(css)

    target = (
        Path(__file__).resolve().parent.parent
        / "games/static/games/css/machina-scoped.css"
    )
    target.write_text("\n".join(chunks), encoding="utf-8")
    print(f"Wrote {target} ({target.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
