# Generated by Django 4.1.7 on 2023-03-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='year_of_release',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
    ]
