# Generated by Django 4.1.7 on 2023-03-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_publication_list_publisher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('publisher', 'name', 'year')},
        ),
    ]
