# Generated by Django 4.2.1 on 2023-05-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_game_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
