# Generated by Django 4.1.7 on 2023-03-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_list_alter_game_options_listmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.developer'),
        ),
        migrations.AlterField(
            model_name='listmembership',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='games.game'),
        ),
    ]
