# Generated by Django 4.1.7 on 2023-03-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_list_url_alter_game_developer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['name']},
        ),
    ]
