# Generated by Django 4.1.7 on 2023-03-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_list_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('M', 'Main'), ('E', 'End of year')], default='M', max_length=1),
        ),
    ]
