# Generated by Django 4.2.1 on 2023-05-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="order",
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
