# Generated by Django 4.1.7 on 2023-03-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_platform_options_list_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developeralias',
            options={'ordering': ['name'], 'verbose_name_plural': 'Developer aliases'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['type', 'name']},
        ),
    ]
