# Generated by Django 4.2.1 on 2023-08-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_alter_list_options_game_igdb_artwork_id_game_igdb_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="rank",
            field=models.IntegerField(),
        ),
    ]
