# Generated by Django 4.1.7 on 2023-03-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_developeralias_options_alter_list_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developeralias',
            name='developer',
        ),
        migrations.AddField(
            model_name='developeralias',
            name='developers',
            field=models.ManyToManyField(related_name='aliases', to='games.developer'),
        ),
    ]
