# Generated by Django 4.2.1 on 2023-08-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_alter_game_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="igdb_artwork_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="igdb_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
