# Generated by Django 4.2.1 on 2023-08-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_igdb_artwork_id_alter_game_igdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year_of_release',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
