# Generated by Django 4.2.1 on 2023-08-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_description_alter_game_year_of_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='developeralias',
            name='igdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
