# Generated by Django 4.2.1 on 2023-08-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_post_alter_genre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
