# Generated by Django 4.2.1 on 2023-09-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_post_options_post_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='igdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
