# Generated by Django 4.2.1 on 2023-09-10 07:28

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Publication = apps.get_model("games", "Publication")
    for publication in Publication.objects.all():
        publication.slug = slugify(publication.name)
        publication.save()


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_developer_igdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(populate_slugs),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(),
        ),
    ]
