# Generated by Django 4.2.6 on 2023-11-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_game_name_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='decade_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='year_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.CharField(choices=[('A', 'All time'), ('E', 'End of year'), ('M', 'Miscellaneous'), ('D', 'Decade')], default='E', max_length=1),
        ),
    ]
