# Generated by Django 4.2.6 on 2023-11-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_game_decade_rank_game_year_rank_alter_list_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdb_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
