# Generated by Django 5.0.3 on 2024-04-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0022_game_slug_alter_game_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
