# Generated by Django 5.1.7 on 2025-03-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_alter_developer_slug_alter_game_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['order', 'type', 'publisher', 'year', 'name']},
        ),
    ]
