# Generated by Django 5.2.8 on 2025-11-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0025_alter_list_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="igdb_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="developeralias",
            name="igdb_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="igdb_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="modified",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="name_normalized",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="rank",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="year_of_release",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="type",
            field=models.CharField(
                choices=[
                    ("A", "All time"),
                    ("E", "End of year"),
                    ("M", "Miscellaneous"),
                    ("D", "Decade"),
                ],
                db_index=True,
                default="E",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="year",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["year_of_release", "rank"], name="games_game_year_of_04d9d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="list",
            index=models.Index(
                fields=["type", "year"], name="games_list_type_a4e42c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listmembership",
            index=models.Index(
                fields=["list", "rank"], name="games_listm_list_id_b07a78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listmembership",
            index=models.Index(
                fields=["game", "list"], name="games_listm_game_id_6707f5_idx"
            ),
        ),
    ]
