# Generated by Django 5.2.8 on 2025-11-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0027_game_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default="default", max_length=50, unique=True),
                ),
                ("last_full_update", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Site Metadata",
                "verbose_name_plural": "Site Metadata",
            },
        ),
    ]
