# Generated by Django 5.2.8 on 2025-11-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0028_sitemetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developer",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
