# Generated by Django 5.2.8 on 2025-11-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0029_alter_developer_name_alter_game_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="genre",
            index=models.Index(fields=["name"], name="games_genre_name_f4ac62_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["active", "-date"], name="games_post_active_a59e75_idx"
            ),
        ),
    ]
