# Generated by Django 5.2.8 on 2025-11-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0030_genre_games_genre_name_f4ac62_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="decade_rank",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="year_rank",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
