# Generated by Django 5.2.8 on 2025-11-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0032_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="wikidata_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="wikipedia_primary_genre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
