# Generated by Django 5.2.8 on 2025-11-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0033_add_wikipedia_genre_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="wikipedia_all_genres",
            field=models.TextField(blank=True, null=True),
        ),
    ]
