# Generated by Django 5.2.8 on 2025-12-03 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0034_add_wikipedia_all_genres"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="The quote text")),
                (
                    "attribution",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Source of quote (e.g., 'IGN Review', " "'Game dialogue')"
                        ),
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Featured quotes are prioritized for Game of the Day",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created"],
                "indexes": [
                    models.Index(
                        fields=["game", "-is_featured"],
                        name="games_gameq_game_id_710ff2_idx",
                    )
                ],
            },
        ),
    ]
