# Generated by Django 5.2.8 on 2025-12-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0035_gamequote"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_of_the_day_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="The date this game was last selected as Game of the Day",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="is_game_of_the_day",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this game is currently the Game of the Day",
            ),
        ),
    ]
