# Generated by Django 5.2.8 on 2025-12-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0036_add_game_of_the_day_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("date_subscribed", models.DateTimeField(auto_now_add=True)),
                ("is_confirmed", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "confirmation_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
            ],
            options={
                "ordering": ["-date_subscribed"],
                "indexes": [
                    models.Index(
                        fields=["is_confirmed", "is_active"],
                        name="games_subsc_is_conf_c1760b_idx",
                    )
                ],
            },
        ),
    ]
