# Generated by Django 5.2.8 on 2025-12-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0037_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="notification_sent",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Tracks whether email notification has been sent "
                    "for this post (sent only once)."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text=(
                    "⚠️ Checking this box will publish the post and "
                    "send email notifications to all subscribers."
                ),
            ),
        ),
    ]
