# Generated by Django 5.2.8 on 2025-12-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0039_add_wikipedia_page_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="game_of_the_day_date",
        ),
        migrations.RemoveField(
            model_name="game",
            name="is_game_of_the_day",
        ),
    ]
