# Generated by Django 5.2.8 on 2025-12-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0040_remove_game_game_of_the_day_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="wikipedia_lookup_source",
            field=models.CharField(
                blank=True,
                help_text="Lookup method: wikidata, opensearch_year, etc.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="wikipedia_page_title",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Wikipedia page title (e.g., 'Zelda: Breath of the Wild')",
                max_length=300,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="IGDBGameData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "igdb_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="IGDB game ID for this specific version/entry",
                    ),
                ),
                (
                    "artwork_id",
                    models.CharField(
                        db_index=True,
                        help_text="IGDB cover art hash (e.g., 'co1234')",
                        max_length=100,
                    ),
                ),
                ("url", models.URLField(help_text="IGDB game detail page URL")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Primary IGDB record for display (only one per game)",
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="igdb_game_data_set",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "IGDB Game Data",
                "verbose_name_plural": "IGDB Game Data",
                "db_table": "games_igdbgamedata",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="primary_igdb_game_data",
            field=models.OneToOneField(
                blank=True,
                help_text="Primary IGDB game data for display",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_game",
                to="games.igdbgamedata",
            ),
        ),
        migrations.CreateModel(
            name="WikipediaGameData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wikidata_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Wikidata entity ID (e.g., 'Q12345')",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        db_index=True, help_text="Wikipedia page title", max_length=300
                    ),
                ),
                (
                    "primary_genre",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("all_genres", models.TextField(blank=True, null=True)),
                (
                    "lookup_source",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Primary Wikipedia record (one per game)",
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wikipedia_game_data_set",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wikipedia Game Data",
                "verbose_name_plural": "Wikipedia Game Data",
                "db_table": "games_wikipediagamedata",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="primary_wikipedia_game_data",
            field=models.OneToOneField(
                blank=True,
                help_text="Primary Wikipedia game data for display",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_game",
                to="games.wikipediagamedata",
            ),
        ),
        migrations.AddIndex(
            model_name="igdbgamedata",
            index=models.Index(
                fields=["game", "is_primary"], name="games_igdbg_game_id_539497_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="igdbgamedata",
            index=models.Index(
                fields=["igdb_id"], name="games_igdbg_igdb_id_5893a4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="igdbgamedata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("game",),
                name="unique_primary_igdb_per_game",
            ),
        ),
        migrations.AddIndex(
            model_name="wikipediagamedata",
            index=models.Index(
                fields=["game", "is_primary"], name="games_wikip_game_id_da5b77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipediagamedata",
            index=models.Index(
                fields=["wikidata_id"], name="games_wikip_wikidat_b51552_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wikipediagamedata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("game",),
                name="unique_primary_wikipedia_per_game",
            ),
        ),
    ]
