# Generated by Django 5.2.8 on 2025-12-04 19:40

import sys

from django.db import migrations

# Suppress print statements during tests
TEST_MODE = "test" in sys.argv


def migrate_igdb_data(apps, schema_editor):
    """
    Migrate existing IGDB data from deprecated Game fields to IGDBGameData records.
    """
    Game = apps.get_model("games", "Game")
    IGDBGameData = apps.get_model("games", "IGDBGameData")

    games_with_igdb = Game.objects.filter(igdb_id__isnull=False)
    migrated = 0

    for game in games_with_igdb:
        # Create IGDBGameData record from deprecated fields
        igdb_data = IGDBGameData.objects.create(
            game=game,
            igdb_id=game.igdb_id,
            artwork_id=game.igdb_artwork_id or "",
            url=game.igdb_url or "",
            description=game.description or "",
            is_primary=True,
        )

        # Set primary relationship
        game.primary_igdb_game_data = igdb_data
        game.save(update_fields=["primary_igdb_game_data"])
        migrated += 1

    if not TEST_MODE:
        print(f"Migrated IGDB data for {migrated} games")


def migrate_wikipedia_data(apps, schema_editor):
    """
    Migrate Wikipedia data from deprecated Game fields to WikipediaGameData.
    """
    Game = apps.get_model("games", "Game")
    WikipediaGameData = apps.get_model("games", "WikipediaGameData")

    # Migrate games with Wikipedia page title (most specific indicator)
    games_with_wikipedia = Game.objects.filter(
        wikipedia_page_title__isnull=False
    ).exclude(wikipedia_page_title="")
    migrated = 0

    for game in games_with_wikipedia:
        # Create WikipediaGameData record from deprecated fields
        wiki_data = WikipediaGameData.objects.create(
            game=game,
            wikidata_id=game.wikidata_id or "",
            page_title=game.wikipedia_page_title,
            primary_genre=game.wikipedia_primary_genre or "",
            all_genres=game.wikipedia_all_genres or "",
            lookup_source=game.wikipedia_lookup_source or "",
            is_primary=True,
        )

        # Set primary relationship
        game.primary_wikipedia_game_data = wiki_data
        game.save(update_fields=["primary_wikipedia_game_data"])
        migrated += 1

    if not TEST_MODE:
        print(f"Migrated Wikipedia data for {migrated} games")


def reverse_migrate_igdb_data(apps, schema_editor):
    """
    Reverse migration: Copy data to Game deprecated fields.
    """
    IGDBGameData = apps.get_model("games", "IGDBGameData")

    for igdb_data in IGDBGameData.objects.filter(is_primary=True):
        game = igdb_data.game
        game.igdb_artwork_id = igdb_data.artwork_id
        game.igdb_url = igdb_data.url
        game.description = igdb_data.description
        game.save(update_fields=["igdb_artwork_id", "igdb_url", "description"])


def reverse_migrate_wikipedia_data(apps, schema_editor):
    """
    Reverse migration: Copy data to Game deprecated fields.
    """
    WikipediaGameData = apps.get_model("games", "WikipediaGameData")

    for wiki_data in WikipediaGameData.objects.filter(is_primary=True):
        game = wiki_data.game
        game.wikidata_id = wiki_data.wikidata_id
        game.wikipedia_page_title = wiki_data.page_title
        game.wikipedia_primary_genre = wiki_data.primary_genre
        game.wikipedia_all_genres = wiki_data.all_genres
        game.wikipedia_lookup_source = wiki_data.lookup_source
        game.save(
            update_fields=[
                "wikidata_id",
                "wikipedia_page_title",
                "wikipedia_primary_genre",
                "wikipedia_all_genres",
                "wikipedia_lookup_source",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0041_alter_game_wikipedia_lookup_source_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_igdb_data, reverse_migrate_igdb_data),
        migrations.RunPython(migrate_wikipedia_data, reverse_migrate_wikipedia_data),
    ]
