# Generated by Django 5.2.8 on 2025-12-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0043_rename_developer_to_company_studio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="developers",
            new_name="studios",
        ),
    ]
