# Generated by Django 5.2.8 on 2025-12-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0044_rename_developers_to_studios"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="wikipedia_all_genres",
        ),
        migrations.RemoveField(
            model_name="game",
            name="wikipedia_lookup_source",
        ),
        migrations.RemoveField(
            model_name="game",
            name="wikipedia_page_title",
        ),
        migrations.RemoveField(
            model_name="game",
            name="wikipedia_primary_genre",
        ),
        migrations.AlterField(
            model_name="company",
            name="igdb_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="IGDB company ID (from companies endpoint)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="studios",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Game development studios that created this game "
                    "(from IGDB involved_companies)"
                ),
                related_name="games",
                to="games.studio",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="wikidata_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Wikidata entity ID (e.g., 'Q12345')",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="igdb_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="IGDB company ID (from companies endpoint)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wikipediagamedata",
            name="is_primary",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Primary Wikipedia record for display (only one per game)",
            ),
        ),
    ]
