# Generated by Django 5.2.8 on 2025-12-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0045_remove_deprecated_wikipedia_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="igdb_artwork_id",
        ),
        migrations.RemoveField(
            model_name="game",
            name="igdb_url",
        ),
    ]
