# Generated by Django 5.2.8 on 2025-12-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0046_remove_game_igdb_artwork_id_remove_game_igdb_url"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="igdbgamedata",
            name="unique_primary_igdb_per_game",
        ),
        migrations.RemoveConstraint(
            model_name="wikipediagamedata",
            name="unique_primary_wikipedia_per_game",
        ),
        migrations.AlterField(
            model_name="igdbgamedata",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="igdb_game_data_set",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="wikipediagamedata",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wikipedia_game_data_set",
                to="games.game",
            ),
        ),
        migrations.AddConstraint(
            model_name="igdbgamedata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("game__isnull", False)),
                fields=("game",),
                name="unique_primary_igdb_per_game",
            ),
        ),
        migrations.AddConstraint(
            model_name="wikipediagamedata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("game__isnull", False)),
                fields=("game",),
                name="unique_primary_wikipedia_per_game",
            ),
        ),
    ]
