# Generated by Django 5.2.8 on 2025-12-16 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0048_rename_genre_to_igdbgenre_create_wikipediagenre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wikipediagenre",
            options={
                "ordering": ["level", "display_order", "name"],
                "verbose_name": "Wikipedia Genre",
                "verbose_name_plural": "Wikipedia Genres",
            },
        ),
        migrations.RenameIndex(
            model_name="igdbgenre",
            new_name="games_igdbg_name_13c97b_idx",
            old_name="games_genre_name_f4ac62_idx",
        ),
        migrations.RenameIndex(
            model_name="wikipediagenre",
            new_name="games_wikip_name_a5803e_idx",
            old_name="games_wikip_name_idx",
        ),
        migrations.AddField(
            model_name="wikipediagenre",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of the genre"
            ),
        ),
        migrations.AddField(
            model_name="wikipediagenre",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="Manual ordering within parent category",
            ),
        ),
        migrations.AddField(
            model_name="wikipediagenre",
            name="icon_name",
            field=models.CharField(
                blank=True,
                help_text="Icon identifier for UI (e.g., 'genre-action')",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="wikipediagenre",
            name="level",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="Hierarchy depth: 0=root, 1=category, 2+=subgenre",
            ),
        ),
        migrations.AddField(
            model_name="wikipediagenre",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent genre (NULL for root categories)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="games.wikipediagenre",
            ),
        ),
        migrations.AddField(
            model_name="wikipediagenre",
            name="path",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Full hierarchy path (e.g., 'Action > Shooter > FPS')",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="wikipediagenre",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier",
                max_length=110,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="wikipediagenre",
            index=models.Index(
                fields=["parent", "level"], name="games_wikip_parent__412946_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wikipediagenre",
            index=models.Index(
                fields=["level", "display_order"], name="games_wikip_level_03fb4d_idx"
            ),
        ),
    ]
