# Generated by Django 5.2.8 on 2025-12-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0051_normalize_wikipedia_game_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=210, unique=True)),
                ("igdb_id", models.IntegerField(db_index=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "Series",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="series",
            field=models.ManyToManyField(
                blank=True,
                help_text="Game series from IGDB (e.g., 'Mario Kart')",
                related_name="games",
                to="games.series",
            ),
        ),
    ]
