# Generated by Django 5.2.8 on 2025-12-29 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0056_cleanup_studio_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="developer",
            options={"ordering": ["name"], "verbose_name_plural": "Developers"},
        ),
        migrations.AddField(
            model_name="platform",
            name="year_end",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Year platform discontinued (null = still active)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="platform",
            name="year_start",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Year platform became active", null=True
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="igdb_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="IGDB developer ID (from companies endpoint)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="developer",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent developer in the ownership hierarchy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsidiaries",
                to="games.developer",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="series",
            field=models.ManyToManyField(
                blank=True,
                help_text="Game series from IGDB (e.g., 'Mario Kart')",
                related_name="games",
                to="games.series",
            ),
        ),
    ]
