# Generated by Django 5.2.8 on 2025-12-30 18:57

from django.db import migrations


def migrate_users_and_subscribers(apps, schema_editor):
    """
    Migrate existing auth.User records to games.User and merge Subscriber data.

    This migration:
    1. Copies all existing auth.User records to games.User
    2. For users with matching Subscriber emails, merges subscription data
    3. Creates games.User records for remaining Subscribers (no account)
       with unusable passwords - they can claim via password reset
    """
    from django.contrib.auth.hashers import make_password
    from django.db import connection

    NewUser = apps.get_model("games", "User")
    Subscriber = apps.get_model("games", "Subscriber")

    migrated_subscriber_emails = set()

    # Step 1: Migrate existing users from auth_user table directly
    # We can't use apps.get_model("auth", "User") since it's been swapped,
    # so we query the database directly
    old_users = []
    with connection.cursor() as cursor:
        # Check if auth_user table exists (may not on fresh database)
        try:
            cursor.execute(
                """
                SELECT id, password, last_login, is_superuser, username,
                       first_name, last_name, email, is_staff, is_active, date_joined
                FROM auth_user
            """
            )
            columns = [col[0] for col in cursor.description]
            old_users = [dict(zip(columns, row)) for row in cursor.fetchall()]
        except Exception:
            # Table doesn't exist - fresh database, no users to migrate
            pass

    for old_user in old_users:
        # Check if user email matches a subscriber
        subscriber = None
        if old_user["email"]:
            subscriber = Subscriber.objects.filter(
                email__iexact=old_user["email"]
            ).first()
            if subscriber:
                migrated_subscriber_emails.add(subscriber.email.lower())

        new_user = NewUser(
            id=old_user["id"],
            password=old_user["password"],
            last_login=old_user["last_login"],
            is_superuser=old_user["is_superuser"],
            username=old_user["username"],
            first_name=old_user["first_name"],
            last_name=old_user["last_name"],
            email=old_user["email"],
            is_staff=old_user["is_staff"],
            is_active=old_user["is_active"],
            date_joined=old_user["date_joined"],
            # Subscription fields from Subscriber if matched
            email_subscribed=subscriber.is_active if subscriber else False,
            email_confirmed=subscriber.is_confirmed if subscriber else False,
            confirmation_token=subscriber.confirmation_token if subscriber else None,
            unsubscribe_token=subscriber.unsubscribe_token if subscriber else None,
            date_subscribed=subscriber.date_subscribed if subscriber else None,
        )
        new_user.save()

        # Copy groups and permissions via raw SQL since we can't use auth.User model
        with connection.cursor() as cursor:
            # Copy group memberships
            cursor.execute(
                """
                SELECT group_id FROM auth_user_groups WHERE user_id = %s
            """,
                [old_user["id"]],
            )
            for (group_id,) in cursor.fetchall():
                new_user.groups.add(group_id)

            # Copy user permissions
            cursor.execute(
                """
                SELECT permission_id FROM auth_user_user_permissions WHERE user_id = %s
            """,
                [old_user["id"]],
            )
            for (permission_id,) in cursor.fetchall():
                new_user.user_permissions.add(permission_id)

    # Update the sequence to avoid conflicts when creating new users
    # This is needed because we inserted users with explicit IDs
    if old_users and connection.vendor == "postgresql":
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT setval('games_user_id_seq',
                    (SELECT COALESCE(MAX(id), 1) FROM games_user), true)
            """
            )

    # Step 2: Create User records for remaining subscribers (no account)
    for subscriber in Subscriber.objects.all():
        # Skip if already migrated with a user
        if subscriber.email.lower() in migrated_subscriber_emails:
            continue

        # Generate a unique username from email
        base_username = subscriber.email.split("@")[0][:140]
        username = base_username
        counter = 1
        while NewUser.objects.filter(username=username).exists():
            username = f"{base_username}_{counter}"
            counter += 1

        new_user = NewUser(
            username=username,
            email=subscriber.email,
            # Set unusable password - user can claim via password reset
            password=make_password(None),
            is_active=True,
            is_staff=False,
            is_superuser=False,
            email_subscribed=subscriber.is_active,
            email_confirmed=subscriber.is_confirmed,
            confirmation_token=subscriber.confirmation_token,
            unsubscribe_token=subscriber.unsubscribe_token,
            date_subscribed=subscriber.date_subscribed,
        )
        new_user.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - delete all games.User records.

    WARNING: This will lose all user data! Only use for development.
    """
    NewUser = apps.get_model("games", "User")
    NewUser.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0060_custom_user_model"),
        # Note: 0060 has run_before 0059, so 0059 runs after 0060.
        # We depend on 0059 for the Subscriber model.
        ("games", "0059_alter_game_series_userprofile"),
    ]

    operations = [
        migrations.RunPython(migrate_users_and_subscribers, reverse_migration),
    ]
