# Generated by Django 5.2.8 on 2025-12-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0061_migrate_users_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscriber",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
