# Generated by Django 5.2.8 on 2025-12-30 20:42
# Modified to handle both production (games.User with fields) and fresh databases (core.User)

from django.db import connection, migrations


def get_table_columns(table_name):
    """Get list of column names for a table, database-agnostic."""
    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute(f"PRAGMA table_info({table_name})")
            return [row[1] for row in cursor.fetchall()]
        elif connection.vendor == "postgresql":
            cursor.execute(
                """
                SELECT column_name FROM information_schema.columns
                WHERE table_name = %s
                """,
                [table_name],
            )
            return [row[0] for row in cursor.fetchall()]
        else:
            # Fallback: try to get columns from Django's introspection
            return connection.introspection.get_table_description(cursor, table_name)


def migrate_email_confirmed_to_emailaddress(apps, schema_editor):
    """
    Create EmailAddress records for existing subscribers who don't have one.
    Set verified=True if email_confirmed was True.

    Note: For fresh databases (tests, new installs), the email_confirmed field
    doesn't exist since core.User was created without it. In that case, skip migration.
    """
    # Check if email_confirmed column exists in the database table
    columns = get_table_columns("games_user")
    if "email_confirmed" not in columns:
        # Column doesn't exist (fresh database) - nothing to migrate
        return

    User = apps.get_model("core", "User")
    EmailAddress = apps.get_model("account", "EmailAddress")

    for user in User.objects.filter(email__isnull=False).exclude(email=""):
        # Check if EmailAddress already exists
        if not EmailAddress.objects.filter(user=user, email__iexact=user.email).exists():
            # Create EmailAddress with verified status based on old email_confirmed
            # Use raw SQL since the field might not be in the model state
            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT email_confirmed FROM games_user WHERE id = %s", [user.id]
                )
                row = cursor.fetchone()
                email_confirmed = row[0] if row else False

            EmailAddress.objects.create(
                user=user,
                email=user.email,
                verified=email_confirmed,
                primary=True,
            )


def remove_fields_if_exist(apps, schema_editor):
    """
    Remove email_confirmed and confirmation_token fields if they exist.
    Also remove the user_subscription_idx index if it exists.
    """
    # Check what columns exist
    columns = get_table_columns("games_user")

    # Remove index if it exists
    if "email_confirmed" in columns:
        try:
            with connection.cursor() as cursor:
                cursor.execute("DROP INDEX IF EXISTS user_subscription_idx")
        except Exception:
            pass  # Index might not exist

    # Remove columns if they exist (SQLite doesn't support DROP COLUMN in all versions)
    if "confirmation_token" in columns or "email_confirmed" in columns:
        # For SQLite, we need to recreate the table without these columns
        # This is complex, so we'll use Django's schema editor if possible
        # For production (PostgreSQL), this is simpler
        db_engine = connection.vendor

        if db_engine == "postgresql":
            with connection.cursor() as cursor:
                if "confirmation_token" in columns:
                    cursor.execute(
                        "ALTER TABLE games_user DROP COLUMN IF EXISTS confirmation_token"
                    )
                if "email_confirmed" in columns:
                    cursor.execute(
                        "ALTER TABLE games_user DROP COLUMN IF EXISTS email_confirmed"
                    )
        # For SQLite in tests, the columns will be ignored since they're not in the model


def reverse_migration(apps, schema_editor):
    """
    No-op reverse - EmailAddress records are fine to keep, and fields don't need to come back.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0062_remove_old_models"),
        ("account", "0001_initial"),  # Ensure allauth's EmailAddress model exists
        ("core", "0001_initial"),  # Ensure core.User exists
    ]

    operations = [
        # First migrate data to EmailAddress
        migrations.RunPython(
            migrate_email_confirmed_to_emailaddress,
            reverse_migration,
        ),
        # Then remove the old fields if they exist
        migrations.RunPython(
            remove_fields_if_exist,
            reverse_migration,
        ),
        # Update Django's state to reflect that these fields are removed from games.User
        # This is state-only since the actual model is now core.User
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="user",
                    name="user_subscription_idx",
                ),
                migrations.RemoveField(
                    model_name="user",
                    name="confirmation_token",
                ),
                migrations.RemoveField(
                    model_name="user",
                    name="email_confirmed",
                ),
            ],
            database_operations=[],  # Already handled above
        ),
    ]
