# Generated by Django 5.2.8 on 2025-12-30 20:42
#
# Originally removed email_confirmed and confirmation_token fields from games.User.
# Now a no-op because User model was moved to core.User without these fields.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0062_remove_old_models"),
    ]

    operations = [
        # No-op: User model was moved to core.User without email_confirmed
        # and confirmation_token fields, so there's nothing to remove.
    ]
