# Generated by Django 5.2.8 on 2025-12-30 20:42

from django.db import migrations


def migrate_email_confirmed_to_emailaddress(apps, schema_editor):
    """
    Create EmailAddress records for existing subscribers who don't have one.
    Set verified=True if email_confirmed was True.
    """
    User = apps.get_model("games", "User")
    EmailAddress = apps.get_model("account", "EmailAddress")

    for user in User.objects.filter(email__isnull=False).exclude(email=""):
        # Check if EmailAddress already exists
        if not EmailAddress.objects.filter(
            user=user, email__iexact=user.email
        ).exists():
            # Create EmailAddress with verified status based on old email_confirmed
            EmailAddress.objects.create(
                user=user,
                email=user.email,
                verified=user.email_confirmed,
                primary=True,
            )


def reverse_migration(apps, schema_editor):
    """
    No-op reverse - EmailAddress records are fine to keep.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0062_remove_old_models"),
        ("account", "0001_initial"),  # Ensure allauth's EmailAddress model exists
    ]

    operations = [
        # First migrate data to EmailAddress
        migrations.RunPython(
            migrate_email_confirmed_to_emailaddress,
            reverse_migration,
        ),
        # Then remove the old fields
        migrations.RemoveIndex(
            model_name="user",
            name="user_subscription_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="confirmation_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_confirmed",
        ),
    ]
