# Generated by Django 5.2.8 on 2025-12-30

from django.db import migrations


def update_fk_constraints(apps, schema_editor):
    """
    Update foreign key constraints from auth_user to games_user.

    After migrating users from auth_user to games_user (with same IDs),
    we need to update FK constraints to point to games_user.
    """
    from django.db import connection

    if connection.vendor != "postgresql":
        # Only needed for PostgreSQL; SQLite doesn't enforce FK constraints the same way
        return

    with connection.cursor() as cursor:
        # Define FKs to update: (table, column, constraint_suffix)
        fks_to_update = [
            ("account_emailaddress", "user_id", "user_id_fk"),
            ("django_admin_log", "user_id", "user_id_fk"),
            ("socialaccount_socialaccount", "user_id", "user_id_fk"),
            ("games_post", "author_id", "author_id_fk"),
        ]

        for table, column, suffix in fks_to_update:
            # Find and drop the existing FK constraint
            cursor.execute(
                """
                SELECT con.conname
                FROM pg_catalog.pg_constraint con
                INNER JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
                INNER JOIN pg_catalog.pg_namespace nsp ON nsp.oid = rel.relnamespace
                WHERE rel.relname = %s
                AND con.contype = 'f'
                AND con.conname LIKE %s
            """,
                [table, f"%{column}%"],
            )
            result = cursor.fetchone()

            if result:
                constraint_name = result[0]
                # Drop old constraint
                cursor.execute(
                    f'ALTER TABLE "{table}" DROP CONSTRAINT "{constraint_name}"'
                )
                # Add new constraint pointing to games_user
                cursor.execute(
                    f"""
                    ALTER TABLE "{table}"
                    ADD CONSTRAINT "{table}_{suffix}_games"
                    FOREIGN KEY ("{column}")
                    REFERENCES "games_user" ("id")
                    DEFERRABLE INITIALLY DEFERRED
                """
                )


def reverse_fk_constraints(apps, schema_editor):
    """Reverse is complex - would need to restore original constraints."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0063_remove_email_confirmed_fields"),
    ]

    operations = [
        migrations.RunPython(update_fk_constraints, reverse_fk_constraints),
    ]
