# Generated by Django 5.2.8 on 2025-12-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0065_add_played_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="send_notification",
            field=models.BooleanField(
                default=False,
                help_text="Check to send email notification to subscribers when publishing. Only sends if notification hasn't been sent yet.",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether the post is published and visible on the site.",
            ),
        ),
    ]
