# Generated by Django 5.2.8 on 2026-01-03 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0066_post_send_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Brief summary for list views and SEO meta description.",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Article body in Markdown. Images can be embedded using ![alt](url) syntax."
                    ),
                ),
                (
                    "featured_image",
                    models.URLField(
                        blank=True,
                        help_text="URL for the main article image (e.g., from Cloudinary).",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Set automatically when status changes to published.",
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_at"],
                        name="games_artic_status_910f4a_idx",
                    )
                ],
            },
        ),
    ]
