# Generated by Django 5.2.8 on 2026-01-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0068_savedfilterset"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="savedfilterset",
            new_name="games_saved_user_id_b861b3_idx",
            old_name="games_saved_user_id_8a2f3c_idx",
        ),
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=models.TextField(
                blank=True,
                help_text="Summary shown on the blog list page, in search engine results, and when shared on social media. Keep under 160 characters for best SEO.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="savedfilterset",
            name="name",
            field=models.CharField(
                help_text="User-defined or auto-generated filter name", max_length=255
            ),
        ),
    ]
