# Generated by Django 5.2.8 on 2026-01-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0069_increase_savedfilter_name_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="igdbgamedata",
            name="youtube_video_id",
            field=models.CharField(
                blank=True,
                help_text="YouTube video ID from IGDB (first video)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="savedfilterset",
            name="filters",
            field=models.JSONField(
                help_text="Filter configuration: q, start, end, genres, platforms, etc."
            ),
        ),
    ]
