# Generated by Django 5.2.8 on 2026-01-03 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0070_add_youtube_video_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HLTBGameData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "igdb_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="IGDB game ID for reconnection after reimport",
                    ),
                ),
                (
                    "hltb_id",
                    models.CharField(
                        db_index=True,
                        help_text="HowLongToBeat internal game ID",
                        max_length=20,
                    ),
                ),
                (
                    "main_story_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hours to complete main story",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "main_extra_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hours to complete main story + extras",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "completionist_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hours for 100% completion",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Primary HLTB record for display (only one per game)",
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hltb_game_data_set",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "HLTB Game Data",
                "verbose_name_plural": "HLTB Game Data",
                "db_table": "games_hltbgamedata",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="primary_hltb_game_data",
            field=models.OneToOneField(
                blank=True,
                help_text="Primary HLTB game data for playtime display",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_game",
                to="games.hltbgamedata",
            ),
        ),
        migrations.AddIndex(
            model_name="hltbgamedata",
            index=models.Index(
                fields=["game", "is_primary"], name="games_hltbg_game_id_72db5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hltbgamedata",
            index=models.Index(
                fields=["igdb_id"], name="games_hltbg_igdb_id_b9df6a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="hltbgamedata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("game__isnull", False)),
                fields=("game",),
                name="unique_primary_hltb_per_game",
            ),
        ),
    ]
