# Generated by Django 5.2.8 on 2026-01-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0071_add_hltb_game_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipediagamedata",
            name="hltb_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HowLongToBeat ID from Wikidata property P10001",
                max_length=20,
                null=True,
            ),
        ),
    ]
