# Generated by Django 5.2.8 on 2026-01-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0072_add_hltb_id_to_wikipedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="hltbgamedata",
            name="fetch_error",
            field=models.TextField(
                blank=True, default="", help_text="Error message if fetch failed"
            ),
        ),
        migrations.AddField(
            model_name="hltbgamedata",
            name="fetch_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="How the game was matched (wikidata, name_search)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="hltbgamedata",
            name="hltb_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Game name as listed on HowLongToBeat",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="hltbgamedata",
            name="similarity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Name similarity score (0.00-1.00)",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wikipediagamedata",
            name="hltb_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HowLongToBeat ID from Wikidata property P2816",
                max_length=20,
                null=True,
            ),
        ),
    ]
