# Generated by Django 5.2.8 on 2026-01-04 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0073_add_hltb_metadata_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WantToPlayGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("igdb_id", models.IntegerField(db_index=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="want_to_play_by",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="want_to_play_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Want to Play Game",
                "verbose_name_plural": "Want to Play Games",
                "indexes": [
                    models.Index(
                        fields=["user", "game"], name="games_wantt_user_id_cd667d_idx"
                    )
                ],
                "unique_together": {("user", "igdb_id")},
            },
        ),
    ]
