# Generated by Django 5.2.8 on 2026-01-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0074_add_want_to_play_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipediagamedata",
            name="country_of_origin",
            field=models.CharField(
                blank=True,
                help_text="Country of origin from Wikidata P495 (comma-separated)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wikipediagamedata",
            name="game_modes",
            field=models.CharField(
                blank=True,
                help_text="Game modes from Wikidata P404 (comma-separated)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wikipediagamedata",
            name="wikiquote_page_title",
            field=models.CharField(
                blank=True,
                help_text="Wikiquote page title from enwikiquote sitelink",
                max_length=300,
                null=True,
            ),
        ),
    ]
