# Generated by Django 5.2.8 on 2026-01-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0075_add_wikidata_metadata_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikipediaCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=110, unique=True)),
                (
                    "wikidata_id",
                    models.CharField(
                        db_index=True,
                        help_text="Wikidata Q-ID (e.g., 'Q17' for Japan)",
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wikipedia Country",
                "verbose_name_plural": "Wikipedia Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WikipediaGameMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=110, unique=True)),
                (
                    "wikidata_id",
                    models.CharField(
                        db_index=True,
                        help_text="Wikidata Q-ID (e.g., 'Q208850' for Single-player)",
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wikipedia Game Mode",
                "verbose_name_plural": "Wikipedia Game Modes",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="wikipediagamedata",
            name="country_of_origin",
        ),
        migrations.RemoveField(
            model_name="wikipediagamedata",
            name="game_modes",
        ),
        migrations.AddField(
            model_name="game",
            name="wikipedia_countries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Countries of origin from Wikidata P495",
                related_name="games",
                to="games.wikipediacountry",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="wikipedia_game_modes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Game modes from Wikidata P404",
                related_name="games",
                to="games.wikipediagamemode",
            ),
        ),
    ]
