# Generated by Django 5.2.8 on 2026-01-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0076_add_wikipedia_country_gamemode_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="igdb_url",
            field=models.URLField(
                blank=True, help_text="IGDB company detail page URL", null=True
            ),
        ),
    ]
