# Generated by Django 5.2.8 on 2026-01-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0077_add_developer_igdb_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipediagamedata",
            name="steam_app_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Steam AppID from Wikidata property P1733",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProtonDBGameData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "igdb_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="IGDB game ID for reconnection after reimport",
                    ),
                ),
                (
                    "steam_app_id",
                    models.CharField(
                        db_index=True,
                        help_text="Steam AppID used to fetch ProtonDB data",
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("native", "Native"),
                            ("platinum", "Platinum"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                            ("borked", "Borked"),
                            ("pending", "Pending"),
                        ],
                        help_text="ProtonDB compatibility tier",
                        max_length=20,
                    ),
                ),
                (
                    "trending_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("native", "Native"),
                            ("platinum", "Platinum"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                            ("borked", "Borked"),
                            ("pending", "Pending"),
                        ],
                        help_text="Trending compatibility tier based on recent reports",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "report_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of user reports on ProtonDB"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Primary ProtonDB record for display (only one per game)",
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protondb_game_data_set",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProtonDB Game Data",
                "verbose_name_plural": "ProtonDB Game Data",
                "db_table": "games_protondbgamedata",
            },
        ),
        migrations.AddField(
            model_name="game",
            name="primary_protondb_game_data",
            field=models.OneToOneField(
                blank=True,
                help_text="Primary ProtonDB data for Steam Deck compatibility display",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_game",
                to="games.protondbgamedata",
            ),
        ),
        migrations.AddIndex(
            model_name="protondbgamedata",
            index=models.Index(
                fields=["game", "is_primary"], name="games_proto_game_id_9d16cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="protondbgamedata",
            index=models.Index(
                fields=["igdb_id"], name="games_proto_igdb_id_9da1ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="protondbgamedata",
            index=models.Index(
                fields=["steam_app_id"], name="games_proto_steam_a_845f93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="protondbgamedata",
            index=models.Index(fields=["tier"], name="games_proto_tier_0c565c_idx"),
        ),
        migrations.AddConstraint(
            model_name="protondbgamedata",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("game__isnull", False)),
                fields=("game",),
                name="unique_primary_protondb_per_game",
            ),
        ),
    ]
