# Generated by Django 6.0 on 2026-01-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0078_add_protondb_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="media_type",
            field=models.CharField(
                choices=[("G", "Game"), ("B", "Book")],
                db_index=True,
                default="G",
                help_text="Media type this list applies to (games, books, etc.)",
                max_length=1,
            ),
        ),
        migrations.AddIndex(
            model_name="list",
            index=models.Index(
                fields=["media_type"], name="games_list_media_t_61af03_idx"
            ),
        ),
    ]
