# Generated by Django 5.2.8 on 2026-01-05
# Remove games.User from Django state (core.User now owns the table)
#
# This migration removes the User model from games app's state without
# touching the database. The games_user table remains and is now owned
# by core.User.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0079_add_media_type_to_list'),
        # Depend on core.0001 so core.User exists before we remove games.User
        ('core', '0001_initial'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to only update Django's state
        # The games_user table should NOT be deleted - core.User owns it now
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='User',
                ),
            ],
            database_operations=[
                # No database changes - keep the table for core.User
            ],
        ),
    ]
