# Generated by Django 5.2.8 on 2026-01-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0081_alter_developer_name_alter_developer_parent_and_more'),
        ('games', '0081_game_inherit_media_item_base'),
    ]

    operations = [
    ]
