# Generated by Django 5.2.8 on 2026-01-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0082_alter_developer_name_alter_developer_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="primary_protondb_game_data",
        ),
        migrations.DeleteModel(
            name="ProtonDBGameData",
        ),
    ]
