# Generated by Django 5.2.8 on 2026-01-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0083_remove_protondb"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameQuote",
        ),
    ]
