# Generated by Django 5.2.8 on 2026-01-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0084_remove_gamequote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='game',
            name='wikipedia_countries',
        ),
        migrations.RemoveField(
            model_name='game',
            name='wikipedia_game_modes',
        ),
        migrations.RemoveField(
            model_name='igdbgamedata',
            name='description',
        ),
        migrations.DeleteModel(
            name='IGDBGenre',
        ),
        migrations.DeleteModel(
            name='WikipediaCountry',
        ),
        migrations.DeleteModel(
            name='WikipediaGameMode',
        ),
    ]
