# Generated by Django 5.2.8 on 2026-01-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0085_remove_wikipedia_country_gamemode_igdbgenre_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelTable(
            name="list",
            table="games_list",
        ),
        migrations.AlterModelTable(
            name="listmembership",
            table="games_listmembership",
        ),
        migrations.AlterModelTable(
            name="publication",
            table="games_publication",
        ),
    ]
