# Generated by Django 6.0.1 on 2026-06-10 01:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_conversation", "0013_auto_20201220_1745"),
        ("games", "0103_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="forum_topic",
            field=models.OneToOneField(
                blank=True,
                help_text="Auto-created forum topic where this publication is discussed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publication",
                to="forum_conversation.topic",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="reputation_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Editorial reputation score (0-100). Shown at the top of the publication's forum discussion topic.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
