# Generated by Django 6.0.1 on 2026-06-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0104_publication_forum_topic_publication_reputation_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="reputation_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Editorial reputation score. Shown at the top of the publication's forum discussion topic.",
                null=True,
            ),
        ),
    ]
