# Generated by Django 6.0.1 on 2026-06-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0105_alter_publication_reputation_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="forum_topic",
        ),
        migrations.AlterField(
            model_name="publication",
            name="reputation_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Editorial reputation score. Shown in the consolidated 'Publication reputation scores' forum topic.",
                null=True,
            ),
        ),
    ]
