# Generated by Django 6.0.1 on 2026-06-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0106_remove_publication_forum_topic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier",
                max_length=110,
                null=True,
                unique=True,
            ),
        ),
    ]
